# Generated by Django 2.2.2 on 2019-06-10 19:06

from django.db import migrations
import tagging.fields


class Migration(migrations.Migration):

    dependencies = [
        ('crowdfunder', '0002_user_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='tags',
            field=tagging.fields.TagField(blank=True, max_length=255),
        ),
    ]
