# Generated by Django 2.1.5 on 2019-06-07 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crowdfunder', '0002_auto_20190607_0444'),
        ('crowdfunder', '0002_auto_20190607_1415'),
    ]

    operations = [
    ]
