# Generated by Django 2.2.1 on 2019-06-07 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crowdfunder', '0002_auto_20190607_1415'),
        ('crowdfunder', '0002_auto_20190607_0444'),
    ]

    operations = [
    ]
