# Generated by Django 2.2.1 on 2019-06-10 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowdfunder', '0003_project_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('art', 'Arts'), ('c&i', 'Comics & Illustration'), ('d&t', 'Design & Tech'), ('film', 'Film'), ('f&c', 'Food & Craft'), ('game', 'Games'), ('music', 'Music')], default='art', max_length=255),
        ),
    ]
