# Generated by Django 2.2.2 on 2019-06-07 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crowdfunder', '0003_merge_20190607_1500'),
        ('crowdfunder', '0003_merge_20190607_1514'),
        ('crowdfunder', '0003_merge_20190607_1459'),
    ]

    operations = [
    ]
