# Generated by Django 2.2.1 on 2019-06-10 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowdfunder', '0004_auto_20190610_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('Arts', 'Arts'), ('Comics & Illustration', 'Comics & Illustration'), ('Design & Tech', 'Design & Tech'), ('Film', 'Film'), ('Food & Craft', 'Food & Craft'), ('Games', 'Games'), ('Music', 'Music')], default='art', max_length=255),
        ),
    ]
