# Generated by Django 2.2.2 on 2019-06-07 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowdfunder', '0005_auto_20190607_1905'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='expired',
            field=models.BooleanField(default=False),
        ),
    ]
