# Generated by Django 2.2.1 on 2019-06-07 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crowdfunder', '0004_merge_20190607_1745'),
        ('crowdfunder', '0005_auto_20190607_1905'),
    ]

    operations = [
    ]
