# Generated by Django 2.2.2 on 2019-06-07 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowdfunder', '0006_project_expired'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='goal_reached',
            field=models.BooleanField(default=False),
        ),
    ]
