# Generated by Django 2.2.1 on 2019-06-10 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crowdfunder', '0003_project_tags'),
        ('crowdfunder', '0007_auto_20190610_2012'),
    ]

    operations = [
    ]
