# Generated by Django 2.2.2 on 2019-06-10 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowdfunder', '0008_reward_limit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reward',
            name='limit',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
