# Generated by Django 2.2.2 on 2019-06-10 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crowdfunder', '0008_merge_20190610_2125'),
        ('crowdfunder', '0008_merge_20190610_2138'),
    ]

    operations = [
    ]
