# Generated by Django 2.2.2 on 2019-07-29 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowdfunder', '0009_merge_20190610_2143'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='image',
            field=models.ImageField(default=1, upload_to='project-image'),
            preserve_default=False,
        ),
    ]
