# Generated by Django 2.2.2 on 2019-07-30 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowdfunder', '0011_auto_20190729_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='project-image/'),
        ),
    ]
